### ISSUE TITLE
Support for DHCP options (like static routes, alternate DNS server, etc)

### ISSUE THREAD

**Issue by mikejuni** [openwrt/odhcpd#19]
Hi,

I'm now using some custom dnsmasq options in OpenWRT to issue static routes, alternate default gateway and DNS servers. However these options does not exist in odhcpd.

Would be nice if these could be supported in order to completely replace the DHCP functions in dnsmasq in OpenWRT.

**Comment by mehlis** [comment]
I implemented the "alternative default gateway", it's called router option in the RFC
alternative DNS servers as possible right now: use "dns" option :)

@mikejuni can you try/review https://github.com/mehlis/odhcpd/compare/implement-dhcp4-router-config?expand=1

I can try this with openwrt on 12th august, if new code is working I'll open a PR!

**Comment by sbyx** [comment]
Patch looks good to me. Feel free to make a PR and I will merge it.

**Comment by mehlis** [comment]
@mikejuni https://github.com/sbyx/odhcpd/pull/20 is merged, from my perspective odhcpd is a replacement for dnsmasq now

@sbyx this issue is addressed from my point of view

**Comment by mikejuni** [comment]
I've reviewed the relevant patches. Noted that it unfortunately still does not provide the configuration options that I've been using in DNSMASQ. I've a couple of DHCP clients (not all, only a few) that would actually be routed through an alternative router and assigned a different DNS. This means that in the configuration section "host" it should allow overriding default DNS and gateway, or better, allowing allocation of different static routes as well.

I understand that this is very complex but DNSMASQ for now works very well doing so, plus with an ipv6 enabled DNSMASQ it also allocates IPv6 address for my SIXXS tunnel as well.

**Comment by mikken** [comment]
This is a desired feature for me, too. What I miss:
- Advertise search domain in DHCPv4 option 15, not only option 119. Some software expect that.
- Serve NTP server list with DHCPv4 and DHCPv6.
- (unrelated)Put current lease list somewhere in /tmp, like dnsmasq does

**Comment by thalamus** [comment]
This feature would be very useful. Currently I'm using a few dhcp options with dnsmasq, and I would much prefer to use odhcpd wholly instead.

The options I'm currently using with dnsmasq are:

list dhcp_option '43,01:04:00:00:00:02' - disables NetBIOS
list dhcp_option '252,"\n"' - stops Windows asking for proxy information
list dhcp_option '15,lan' - search domain
list dhcp_option '6,10.10.10.254' - dns server (because dnsmasq is in parallel with unbound)

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by serial115200** [comment]
Any news on it?

**Comment by kitchung** [comment]
Any news on it?

**Comment by fsa** [comment]
Similar problem. I don't see any reason to install Dnsmasq, it only needs DHCPv4. I need option 108 so that clients that can xlat do not request an IPv4 address.

**Comment by Alphix** [comment]
FWIW, I'm working on it. The current plan is to implement it both for DHCPv4 and DHCPV6. I also plan to add support for the options both on a per-static lease level and a per-interface level. But it'll take some time... :)

**Comment by jip149** [comment]
Is this still being worked on?

**Comment by Alphix** [comment]
> Is this still being worked on?

Yes, I intentionally paused the work a bit during the release of 25.12 because it'll end up being a pretty intrusive change, and I'm targeting the next release for it...

**Comment by DeViLRuNNeR-dev** [comment]
Is still on the roadmap?
I ran into similar trouble deciding I had enough of the dnsmasq weirdness (_wanting to offer two core network features in one process_).  

I have several ipv4 only clients and cannot seem to get dhcp options (43, 252, 42 ,15 and 119) send using odhcpd daemon on ipv4 only.

_running 2026.06.29~5d7be43f-r1_
