### ISSUE TITLE
relay mode failed, maybe caused by upstream router's cache not updated

### ISSUE THREAD

**Issue by crccw** [openwrt/odhcpd#25]
I'm running odhcpd in relay mode, but pc in LAN fail to ping ipv6.google.com

Using tcpdump, I found that NA is sent without O flag, while other host(not behind a router)'s NA has O flag. 

Would it be possible that the upstream router's cache is not updated due to the lack of O flag in NA? If so, is there a way to work it around?

I'm running the 2014-08-23-24452e1e3e9adfd9d8e183db1aa589f77727f5a7 version of odhcpd.

IPv6 on the router is working ok.

**Comment by sbyx** [comment]
Should work now.

**Comment by crccw** [comment]
still not working.

And setting relay will make ipv4 network is unreachable...
